var Game = {};
Game.EPS = Math.pow(10, -6);
Game.NUMINTERPOLATIONPOINTS = 6;
Game.SPHERESEGMENTS = 12;
Game.CUBESIZE = 2;
Game.ALIGNOFFSET = Math.sqrt(2)*Game.CUBESIZE/2 + 0.05;
Game.NEXTLVLTIMEOUT = 5000;     // time until the win message is cleared and next level is initialized
Game.WINMSG =  " Win!";
Game.LOSEMSG = "Lose!";
Game.MAXVERTICES = 50;